const { SlashCommandBuilder } = require('discord.js');
const { EmbedBuilder } = require('discord.js');

const quotes =[
		"\"May the Force be with you.\"",
		"\"There's no place like home.\"",
		"\"I'm the king of the world!\"",
		"\"Carpe diem. Seize the day, boys. Make your lives extraordinary.\"",
		"\"Elementary, my dear Watson.\"",
		"\"It's alive! It's alive!\"",
		"\"My mama always said life was like a box of chocolates. You never know what you're gonna get.\"",
		"\"I'll be back.\"",
		"\"You're gonna need a bigger boat.\"",
		"\"Here's looking at you, kid.\"",
		"\"My precious.\"",
		"\"Houston, we have a problem.\"",
		"\"There's no crying in baseball!\"",
		"\"E.T. phone home.\"",
		"\"You can't handle the truth!\"",
		"\"A martini. Shaken, not stirred.\"",
		"\"Life is a banquet, and most poor suckers are starving to death!\"",
		"\"If you build it, he will come.\"",
		"\"The stuff that dreams are made of.\"",
		"\"Magic Mirror on the wall, who is the fairest one of all?\"",
		"\"Keep your friends close, but your enemies closer.\"",
		"\"I am your father.\"",
		"\"Just keep swimming.\"",
		"\"Today, I consider myself the luckiest man on the face of the earth.\"",
		"\"You is kind. You is smart. You is important.\"",
		"\"What we've got here is failure to communicate.\"",
		"\"Hasta la vista, baby.\"",
		"\"You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am.\"",
		"\"Bond. James Bond\".",
		"\"You talking to me?\"",
		"\"Roads? Where we're going we don't need roads.\"",
		"\"That'll do, pig. That'll do.\"",
		"\"I'm walking here! I'm walking here!\"",
		"\"It was beauty killed the beast.\"",
		"\"Stella! Hey, Stella!\"",
		"\"As if!\"",
		"\"Here\'s Johnny!\"",
		"\"Rosebud.\"",
		"\"I'll have what she's having.\"",
		"\"Inconceivable!\"",
		"\"All right, Mr. DeMille, I'm ready for my close-up.\"",
		"\"Fasten your seatbelts. It's going to be a bumpy night.\"",
		"\"Nobody puts Baby in a corner.\"",
		"\"Well, nobody's perfect.\"",
		"\"“Snap out of it!\"",
		"\"You had me at hello.\"",
		"\"They may take our lives, but they\'ll never take our freedom!\"",
		"\"To infinity and beyond!\"",
		"\"You\’re killin\’ me, Smalls.\"",
		"\"Toto, I've a feeling we're not in Kansas anymore.\""		
];

const qouteTitle = [
	"-Star Wars, 1977",
	"-The Wizard of Oz, 1939",
	"-Titanic, 1997",
	"-Dead Poets Society, 1989",
	"-The Adventures of Sherlock Holmes, 1939",
	"-Frankenstein, 1931",
	"-Forrest Gump, 1994",
	"-The Terminator, 1984",
	"-Jaws, 1975",
	"-Casablanca,1942",
	"-The Lord of the Rings: Two Towers, 2002",
	"-Apollo 13, 1995",
	"-A League of Their Own, 1992",
	"-E.T. the Extra-Terrestrial, 1982",
	"-A Few Good Men, 1992",
	"-Goldfinger, 1964",
	"-Auntie Mame, 1958",
	"-Field of Dreams, 1989",
	"-The Maltese Falcon, 1941",
	"-Snow White and the Seven Dwarfs, 1937",
	"-The Godfather Part II, 1974",
	"-Star Wars Episode V: The Empire Strikes Back, 1980",
	"-Finding Nemo, 2003",
	"-The Pride of the Yankees, 1942",
	"-The Help, 2011",
	"-Cool Hand Luke, 1967",
	"-Terminator 2: Judgment Day, 1991",
	"-On the Waterfront, 1954",
	"-Dr. No, 1962",
	"-Taxi Driver, 1976",
	"-Back to the Future, 1985",
	"-Babe, 1995",
	"-Midnight Cowboy, 1969",
	"-King Kong, 1933",
	"-A Streetcar Named Desire, 1951",
	"-Clueless, 1995",
	"-The Shining, 1980",
	"-Citizen Kane, 1941",
	"-When Harry Met Sally, 1989",
	"-The Princess Bride, 1987",
	"-Sunset Boulevard, 1950",
	"-All About Eve, 1950",
	"-Dirty Dancing, 1987",
	"-Some Like it Hot, 1959",
	"-Moonstruck, 1987",
	"-Jerry Maguire, 1996",
	"-Braveheart, 1995",
	"-Toy Story, 1995",
	"-The Sandlot, 1993",
	"-The Wizard of Oz, 1939"		
];

const movieURL = [
	"https://en.wikipedia.org/wiki/Star_Wars_(film)",
	"https://en.wikipedia.org/wiki/The_Wizard_of_Oz_(1939_film)",
	"https://en.wikipedia.org/wiki/Titanic_(1997_film)",
	"https://en.wikipedia.org/wiki/Dead_Poets_Society",
	"https://en.wikipedia.org/wiki/The_Adventures_of_Sherlock_Holmes_(film)",
	"https://en.wikipedia.org/wiki/Frankenstein_(1931_film)",
	"https://en.wikipedia.org/wiki/Forrest_Gump",
	"https://en.wikipedia.org/wiki/The_Terminator",
	"https://en.wikipedia.org/wiki/Jaws_(film)",
	"https://da.wikipedia.org/wiki/Casablanca_(film)",
	"https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Two_Towers",
	"https://da.wikipedia.org/wiki/Apollo_13_(film)",
	"https://en.wikipedia.org/wiki/A_League_of_Their_Own",
	"https://en.wikipedia.org/wiki/E.T._the_Extra-Terrestrial",
	"https://en.wikipedia.org/wiki/A_Few_Good_Men",
	"https://en.wikipedia.org/wiki/Goldfinger_(film)",
	"https://en.wikipedia.org/wiki/Auntie_Mame_(film)",
	"https://en.wikipedia.org/wiki/Field_of_Dreams",
	"https://en.wikipedia.org/wiki/The_Maltese_Falcon_(1941_film)",
	"https://en.wikipedia.org/wiki/Snow_White_and_the_Seven_Dwarfs_(1937_film)",
	"https://en.wikipedia.org/wiki/The_Godfather_Part_II",
	"https://en.wikipedia.org/wiki/The_Empire_Strikes_Back",
	"https://en.wikipedia.org/wiki/Finding_Nemo",
	"https://en.wikipedia.org/wiki/The_Pride_of_the_Yankees",
	"https://en.wikipedia.org/wiki/The_Help_(film)",
	"https://en.wikipedia.org/wiki/Cool_Hand_Luke",
	"https://en.wikipedia.org/wiki/Terminator_2:_Judgment_Day",
	"https://en.wikipedia.org/wiki/On_the_Waterfront",
	"https://en.wikipedia.org/wiki/Dr._No_(film)",
	"https://en.wikipedia.org/wiki/Taxi_Driver",
	"https://en.wikipedia.org/wiki/Back_to_the_Future",
	"https://en.wikipedia.org/wiki/Babe_(film)",
	"https://en.wikipedia.org/wiki/Midnight_Cowboy",
	"https://en.wikipedia.org/wiki/King_Kong_(1933_film)",
	"https://en.wikipedia.org/wiki/A_Streetcar_Named_Desire_(1951_film)",
	"https://en.wikipedia.org/wiki/Clueless",
	"https://en.wikipedia.org/wiki/The_Shining_(film)",
	"https://da.wikipedia.org/wiki/Citizen_Kane",
	"https://en.wikipedia.org/wiki/When_Harry_Met_Sally...",
	"https://en.wikipedia.org/wiki/The_Princess_Bride_(film)",
	"https://en.wikipedia.org/wiki/Sunset_Boulevard_(film)",
	"https://en.wikipedia.org/wiki/All_About_Eve",
	"https://en.wikipedia.org/wiki/Dirty_Dancing",
	"https://en.wikipedia.org/wiki/Some_Like_It_Hot",
	"https://en.wikipedia.org/wiki/Moonstruck",
	"https://en.wikipedia.org/wiki/Jerry_Maguire",
	"https://da.wikipedia.org/wiki/Braveheart",
	"https://en.wikipedia.org/wiki/Toy_Story",
	"https://en.wikipedia.org/wiki/The_Sandlot",
	"https://en.wikipedia.org/wiki/The_Wizard_of_Oz_(1939_film)"		
];

const movieThumbnail = [
	"https://en.wikipedia.org/wiki/Star_Wars_(film)",
	"https://en.wikipedia.org/wiki/The_Wizard_of_Oz_(1939_film)",
	"https://en.wikipedia.org/wiki/Titanic_(1997_film)",
	"https://en.wikipedia.org/wiki/Dead_Poets_Society",
	"https://en.wikipedia.org/wiki/The_Adventures_of_Sherlock_Holmes_(film)",
	"https://en.wikipedia.org/wiki/Frankenstein_(1931_film)",
	"https://en.wikipedia.org/wiki/Forrest_Gump",
	"https://en.wikipedia.org/wiki/The_Terminator",
	"https://en.wikipedia.org/wiki/Jaws_(film)",
	"https://da.wikipedia.org/wiki/Casablanca_(film)",
	"https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Two_Towers",
	"https://da.wikipedia.org/wiki/Apollo_13_(film)",
	"https://en.wikipedia.org/wiki/A_League_of_Their_Own",
	"https://en.wikipedia.org/wiki/E.T._the_Extra-Terrestrial",
	"https://en.wikipedia.org/wiki/A_Few_Good_Men",
	"https://en.wikipedia.org/wiki/Goldfinger_(film)",
	"https://en.wikipedia.org/wiki/Auntie_Mame_(film)",
	"https://en.wikipedia.org/wiki/Field_of_Dreams",
	"https://en.wikipedia.org/wiki/The_Maltese_Falcon_(1941_film)",
	"https://en.wikipedia.org/wiki/Snow_White_and_the_Seven_Dwarfs_(1937_film)",
	"https://en.wikipedia.org/wiki/The_Godfather_Part_II",
	"https://en.wikipedia.org/wiki/The_Empire_Strikes_Back",
	"https://en.wikipedia.org/wiki/Finding_Nemo",
	"https://en.wikipedia.org/wiki/The_Pride_of_the_Yankees",
	"https://en.wikipedia.org/wiki/The_Help_(film)",
	"https://en.wikipedia.org/wiki/Cool_Hand_Luke",
	"https://en.wikipedia.org/wiki/Terminator_2:_Judgment_Day",
	"https://en.wikipedia.org/wiki/On_the_Waterfront",
	"https://en.wikipedia.org/wiki/Dr._No_(film)",
	"https://en.wikipedia.org/wiki/Taxi_Driver",
	"https://en.wikipedia.org/wiki/Back_to_the_Future",
	"https://en.wikipedia.org/wiki/Babe_(film)",
	"https://en.wikipedia.org/wiki/Midnight_Cowboy",
	"https://en.wikipedia.org/wiki/King_Kong_(1933_film)",
	"https://en.wikipedia.org/wiki/A_Streetcar_Named_Desire_(1951_film)",
	"https://en.wikipedia.org/wiki/Clueless",
	"https://en.wikipedia.org/wiki/The_Shining_(film)",
	"https://da.wikipedia.org/wiki/Citizen_Kane",
	"https://en.wikipedia.org/wiki/When_Harry_Met_Sally...",
	"https://en.wikipedia.org/wiki/The_Princess_Bride_(film)",
	"https://en.wikipedia.org/wiki/Sunset_Boulevard_(film)",
	"https://en.wikipedia.org/wiki/All_About_Eve",
	"https://en.wikipedia.org/wiki/Dirty_Dancing",
	"https://en.wikipedia.org/wiki/Some_Like_It_Hot",
	"https://en.wikipedia.org/wiki/Moonstruck",
	"https://en.wikipedia.org/wiki/Jerry_Maguire",
	"https://da.wikipedia.org/wiki/Braveheart",
	"https://en.wikipedia.org/wiki/Toy_Story",
	"https://en.wikipedia.org/wiki/The_Sandlot",
	"https://en.wikipedia.org/wiki/The_Wizard_of_Oz_(1939_film)"		
];

let ranNum = parseInt(Math.random() * 50);
const exampleEmbed = new EmbedBuilder()
	.setColor(0x0099FF)
	.setTitle(quotes[ranNum])
	.setURL(qouteTitle[ranNum])
	.setDescription(movieURL[ranNum])
	.setThumbnail(movieThumbnail[ranNum])

module.exports = {
	data: new SlashCommandBuilder()
		.setName('quote')
		.setDescription('Reply with a random quote'),
	async execute(interaction) {
		await interaction.reply({ embeds: [exampleEmbed] });
	},
};
